[Build]  CMake install Python dist-info
Part of #58. Install a minimal dist-info alongside the Python sources.
This means attempting to overwrite a CMake installation using
`pip install` will error like:

> ERROR: Cannot uninstall openassetio-mediacreation 1.0.0a7,
> RECORD file not found.
> Hint: The package was installed by cmake.

* `INSTALLER` is used by `pip` to provide the competing packager name
  ("cmake" in the example hint above).
* `METADATA` is mandatory according to the docs. It has the minimal
  contents required to be valid.
* `REQUESTED` is an empty flag file to signal that the package was
  installed individually and not as a dependency of another. Just seemed
  cheap to provide, not really necessary.
* `top_level.txt` contains the top-level namespace names provided by the
  package. Another one that seemed cheap to provide and is not really
  necessary.

Optionally skip installing `.dist-info` metadata directory as part of
installing Python files using a new
`OPENASSETIO_MEDIACREATION_ENABLE_PYTHON_INSTALL_DIST_INFO`
CMake option.

Signed-off-by: Elliot Morris <elliot.morris@foundry.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -99,3 +99,34 @@ jobs:
         run: |
           python -m pip install -r tests/python/requirements.txt
           PYTHONPATH=$(pwd)/build/dist/hybridpython python -m pytest -v
+
+  disallowed_pip_install:
+    name: Disallowed pip install
+    runs-on: ubuntu-latest
+    container:
+      image: aswf/ci-vfxall:2022-clang14.3
+
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Install Traitgen
+        run: python -m pip install openassetio-traitgen==1.0.0a7
+
+      - name: Set Python Root Dir
+        run: echo "Python_ROOT_DIR=$(python -c 'import sys; print(sys.prefix)')" >> $GITHUB_ENV
+
+      - name: Configure CMake build
+        run: >
+          cmake -S . -B build --install-prefix $Python_ROOT_DIR -DOPENASSETIO_MEDIACREATION_GENERATE_PYTHON=ON
+
+      - name: Install package
+        run: cmake --install build
+
+      - name: Attempt to install using pip
+        # The runner has pipefail set, so if either the pip install
+        # succeeds (inverted via `!`) or the grep fails, then the step
+        # will fail.
+        run: >
+          ! python -m pip install --upgrade --force-reinstall openassetio-mediacreation 2>&1
+          | grep "The package was installed by cmake"
+        shell: bash
